name: Orchestrator Pipeline

on:
  workflow_dispatch:

jobs:
  orchestrate:
    runs-on: ubuntu-latest

    env:
      COLLECTOR_REPO: "CreamsCode/collector"
      DL_BUILDER_REPO: "CreamsCode/datalake-builder"
      DM_REPO: "CreamsCode/datamart"
      GRAPH_REPO: "CreamsCode/neo4j-graph-loader"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          gh auth login --with-token <<< "${{ secrets.MY_GITHUB_TOKEN }}"

      - name: Trigger Collector Pipeline
        run: |
          gh workflow run collector.yml --repo $COLLECTOR_REPO \
            -f aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -f aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -f aws_session_token="${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Wait for Collector Completion
        run: |
          echo "Waiting for Collector pipeline to complete..."
          sleep 75

      - name: Trigger Listener Pipeline
        run: |
          gh workflow run datalake-builder.yml --repo $DL_BUILDER_REPO \
            -f aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -f aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -f aws_session_token="${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Wait for Datalake Completion
        run: |
          echo "Waiting for Collector pipeline to complete..."
          sleep 75

      - name: Trigger Datamart Pipeline
        run: |
          gh workflow run datamart.yml --repo $DM_REPO \
            -f aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -f aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -f aws_session_token="${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Wait for Datalake Completion
        run: |
          echo "Waiting for Collector pipeline to complete..."
          sleep 90

      - name: Trigger Graph Pipeline
        run: |
          gh workflow run graph-engine.yml --repo $GRAPH_REPO \
            -f aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -f aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -f aws_session_token="${{ secrets.AWS_SESSION_TOKEN }}"
